const actions = {
  SWITCH_LOGIN: "SWITCH_LOGIN",
  SET_ACCESSTOKEN: "SET_ACCESSTOKEN",
  SET_TOKEN: "SET_TOKEN",
  SHOW_IMAGES_NEWS: "SHOW_IMAGES_NEWS",
  SET_URL_IMAGES: "SET_URL_IMAGES",
  SET_TYPE_EVENTMONEY: " SET_TYPE_EVENTBYMONEY",
  SET_NAME_EVENT: "SET_NAME_EVENT"
};
export { actions };
