const actions = {
  SWITCH_LOGIN: "SWITCH_LOGIN",
  GET_LISTPARTNER: "GET_LISTPARTNER",
  SET_ACCESSTOKEN: "SET_ACCESSTOKEN",
  SET_TOKEN: "SET_TOKEN",
  SHOW_IMAGES_NEWS: "SHOW_IMAGES_NEWS",
  SET_URL_IMAGES: "SET_URL_IMAGES",
  SET_TYPE_EVENTMONEY: " SET_TYPE_EVENTBYMONEY",
  SET_NAME_EVENT: "SET_NAME_EVENT",
  GET_DETAIL_PROMO: "GET_DETAIL_PROMO",
  SWITCH_CREATE_PROMO: "SWITCH_CREATE_PROMO",
  SET_DATA_TYPEPROMO: "SET_DATA_TYPEPROMO",
  ADD_ITEM_PROMO: "ADD_ITEM_PROMO",
  REDUCE_ITEM_PROMO:'REDUCE_ITEM_PROMO',
  SELECT_ITEM_PARNER:"SELECT_ITEM_PARTNER",
  SELECT_NUMB_ITEM_PROMO:"SELECT_NUMB_ITEM_PROMO",
  SELECT_ITEM_INKIND:"SELECT_ITEM_INKIND",
  SELECT_COIN_EVENT:"SELECT_COIN_EVENT",
  RESET_ITEM_PARTNER:"RESET_ITEM_PARTNER"
};
export { actions };
