const actions = {
  SWITCH_LOGIN: "SWITCH_LOGIN",
  GET_LISTPARTNER: "GET_LISTPARTNER",
  SET_ACCESSTOKEN: "SET_ACCESSTOKEN",
  SET_TOKEN: "SET_TOKEN",
  SHOW_IMAGES_NEWS: "SHOW_IMAGES_NEWS",
  SET_URL_IMAGES: "SET_URL_IMAGES",
  SET_TYPE_EVENTMONEY: " SET_TYPE_EVENTBYMONEY",
  SET_NAME_EVENT: "SET_NAME_EVENT",
  GET_DETAIL_PROMO: "GET_DETAIL_PROMO",
  SWITCH_CREATE_PROMO: "SWITCH_CREATE_PROMO",
  SET_DATA_TYPEPROMO: "SET_DATA_TYPEPROMO"
};
export { actions };
